# Generated by Django 4.0.4 on 2022-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='адрес')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='широта')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='долгота')),
                ('save_date', models.DateTimeField(db_index=True, verbose_name='дата актуализации')),
            ],
            options={
                'verbose_name': 'координаты места',
                'verbose_name_plural': 'координаты мест',
            },
        ),
    ]
