# Generated by Django 4.0.4 on 2022-05-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoordinates',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='placecoordinates',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='placecoordinates',
            name='save_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='дата актуализации'),
        ),
    ]
