# Generated by Django 4.0.4 on 2022-05-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_alter_placecoordinates_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecoordinates',
            name='save_date',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='дата актуализации'),
        ),
    ]
