# Generated by Django 4.0.4 on 2022-04-18 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_productsqty_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsqty',
            name='qty',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество'),
            preserve_default=False,
        ),
    ]
