# Generated by Django 4.0.4 on 2022-04-21 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_first_name_order_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsqty',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
