# Generated by Django 4.0.4 on 2022-04-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_productsqty_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsqty',
            old_name='price',
            new_name='order_price',
        ),
    ]
