# Generated by Django 4.0.4 on 2022-04-22 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20220422_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsqty',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
            preserve_default=False,
        ),
    ]
