# Generated by Django 4.0.4 on 2022-04-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_productsqty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('processed', 'Обработанный')], default='unprocessed', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
