# Generated by Django 4.0.4 on 2022-04-25 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='foodcartapp.ProductsQty', to='foodcartapp.product', verbose_name='товары'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('processed', 'Обработанный')], db_index=True, default='unprocessed', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='productsqty',
            name='order_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='productsqty',
            name='quantity',
            field=models.SmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество'),
        ),
    ]
