# Generated by Django 4.0.4 on 2022-04-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('immediate', 'Сразу'), ('card', 'Картой при доставке'), ('cash', 'Наличными при доставке')], db_index=True, default='card', max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
