# Generated by Django 4.0.4 on 2022-05-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('immediate', '✅ Сразу'), ('card', '💳 Картой'), ('cash', '💵 Наличными')], db_index=True, default='card', max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
