# Generated by Django 4.0.4 on 2022-05-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('immediate', '✅ Сразу'), ('card', '💳 Картой'), ('cash', '💵 Наличными')], db_index=True, max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
