# Generated by Django 4.0.4 on 2022-05-13 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsqty',
            name='quantity',
            field=models.SmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
