# Generated by Django 4.0.4 on 2022-05-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_productsqty_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', '✅ Картой на сайте'), ('card', '💳 Картой'), ('cash', '💵 Наличными')], db_index=True, max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
