# Generated by Django 4.0.4 on 2022-05-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsQty',
            new_name='ProductInOrder',
        ),
    ]
